/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingDecouverteRouteImport } from './routes/onboarding.decouverte'
import { Route as OnboardingInitieRouteImport } from './routes/onboarding.initie'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDecouverteRoute = OnboardingDecouverteRouteImport.update({
  id: '/onboarding/decouverte',
  path: '/onboarding/decouverte',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingInitieRoute = OnboardingInitieRouteImport.update({
  id: '/onboarding/initie',
  path: '/onboarding/initie',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding/decouverte': typeof OnboardingDecouverteRoute
  '/onboarding/initie': typeof OnboardingInitieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding/decouverte': typeof OnboardingDecouverteRoute
  '/onboarding/initie': typeof OnboardingInitieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding/decouverte': typeof OnboardingDecouverteRoute
  '/onboarding/initie': typeof OnboardingInitieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/onboarding/decouverte' | '/onboarding/initie'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/onboarding/decouverte' | '/onboarding/initie'
  id: '__root__' | '/' | '/onboarding/decouverte' | '/onboarding/initie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingDecouverteRoute: typeof OnboardingDecouverteRoute
  OnboardingInitieRoute: typeof OnboardingInitieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/decouverte': {
      id: '/onboarding/decouverte'
      path: '/onboarding/decouverte'
      fullPath: '/onboarding/decouverte'
      preLoaderRoute: typeof OnboardingDecouverteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/initie': {
      id: '/onboarding/initie'
      path: '/onboarding/initie'
      fullPath: '/onboarding/initie'
      preLoaderRoute: typeof OnboardingInitieRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingDecouverteRoute: OnboardingDecouverteRoute,
  OnboardingInitieRoute: OnboardingInitieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
